import type { Metadata } from "next";
import Link from "next/link";
import LegalDoc from "@/components/LegalDoc";

export const metadata: Metadata = {
  title: "Privacy Policy — Panogram",
  description: "What Panogram collects, why, who we share it with, and your choices.",
};

export default function PrivacyPage() {
  return (
    <LegalDoc
      title="Privacy Policy"
      updated="June 29, 2026"
      intro={
        <p>
          Panogram (&ldquo;<b>Panogram</b>,&rdquo; &ldquo;we,&rdquo; &ldquo;us&rdquo;) is a spatial
          social platform for immersive media. This policy explains what we collect when you use it,
          why, who we share it with, and the controls you have. We collect the minimum we need to run
          the service and we never sell your personal data.
        </p>
      }
    >
      <h2>1. Who we are</h2>
      <p>
        The service is operated by Unakin LLC, located in Washington, USA. For any privacy question,
        access or deletion request, contact us at <a href="mailto:me@davidpuerto.com">me@davidpuerto.com</a>.
      </p>

      <h2>2. What we collect</h2>
      <ul>
        <li>
          <b>Account data.</b> When you sign in we use a passwordless &ldquo;magic link,&rdquo; so we
          store your <b>email address</b> and the profile you create (handle, display name, bio,
          avatar). We do not store passwords.
        </li>
        <li>
          <b>Content you publish.</b> The panoramic, 360° and 180° media you upload, plus titles,
          locations, descriptions, comments, and the spatial tags (annotations) you place. Published
          content is <b>public by design</b> — anyone, including logged-out visitors, can view it.
        </li>
        <li>
          <b>Location data.</b> If your capture includes geographic information (latitude, longitude,
          heading), or you log a geocache &ldquo;find&rdquo; with coordinates, we store it to power
          maps, bearings and the discovery features. <b>Precise location is sensitive</b> — see
          &ldquo;Your choices&rdquo; for how to limit it.
        </li>
        <li>
          <b>Activity &amp; engagement.</b> Likes, saves, follows, finds, reports and blocks you
          create, so the social features work and so we can keep the community safe.
        </li>
        <li>
          <b>Usage telemetry.</b> We record product events (for example: viewing the feed, entering
          a capture, dragging to explore, publishing) tied to an anonymous per-tab session
          identifier, to understand what works and improve the product. This is not tied to your
          email unless you are signed in.
        </li>
        <li>
          <b>Technical data.</b> Standard server and security logs (such as IP address and
          approximate region, browser type, and timestamps) generated by our hosting and database
          providers.
        </li>
      </ul>

      <h2>3. Why we use it (legal bases)</h2>
      <ul>
        <li><b>To provide the service</b> — sign-in, publishing, the social graph (performance of a contract).</li>
        <li><b>To keep the community safe</b> — reports, blocks, moderation and abuse prevention (legitimate interests; legal obligation).</li>
        <li><b>To improve the product</b> — aggregate analytics on how features are used (legitimate interests; or consent where required).</li>
        <li><b>To communicate with you</b> — sign-in links and essential service notices.</li>
      </ul>

      <h2>4. Who we share it with</h2>
      <p>We share data only with the service providers (processors) that run Panogram:</p>
      <ul>
        <li><b>Supabase</b> — database, authentication and media storage.</li>
        <li><b>DigitalOcean</b> — application hosting.</li>
        <li><b>Resend</b> — transactional email (for example, sign-in links).</li>
        <li><b>Analytics provider</b> — product usage measurement, where enabled.</li>
      </ul>
      <p>
        We may also disclose information if required by law, to enforce our{" "}
        <Link href="/terms">Terms</Link>, or to protect the rights and safety of users and the
        public. We do <b>not</b> sell your personal data.
      </p>

      <h2>5. Cookies &amp; similar technologies</h2>
      <p>
        We use a small number of cookies and local browser storage that are necessary to keep you
        signed in and to remember preferences (such as which notifications you have seen). Our
        analytics may set its own identifiers; where the law requires consent for non-essential
        tracking, we will ask for it.
      </p>

      <h2>6. How long we keep it</h2>
      <p>
        We keep account and content data while your account is active. If you delete content or your
        account, we remove or de-identify the associated personal data within a reasonable period,
        except where we must retain it to comply with the law, resolve disputes, or enforce our
        agreements. Moderation records (reports and their outcomes) may be retained to keep the
        platform safe.
      </p>

      <h2>7. Your choices &amp; rights</h2>
      <ul>
        <li><b>Access, correction, deletion.</b> You can edit your profile and content in-app, and request access to or deletion of your personal data by emailing <a href="mailto:me@davidpuerto.com">me@davidpuerto.com</a>.</li>
        <li><b>Location.</b> You can publish captures without precise coordinates; remove location from media before uploading if you do not want it shared.</li>
        <li><b>Blocking.</b> You can block other users so their content is hidden from you.</li>
        <li><b>Regional rights.</b> Depending on where you live (for example the EEA/UK under GDPR, or California under the CCPA/CPRA), you may have additional rights, including to object to or restrict processing, to portability, and to lodge a complaint with your data-protection authority.</li>
      </ul>

      <h2>8. Children</h2>
      <p>
        Panogram is not for people under <b>13</b> (or the minimum digital-consent age in your
        country, where higher). We do not knowingly collect data from children below that age; if you
        believe a child has provided us data, contact <a href="mailto:me@davidpuerto.com">me@davidpuerto.com</a> and we
        will delete it.
      </p>

      <h2>9. International transfers &amp; security</h2>
      <p>
        Our providers may process data in countries other than yours; where required we rely on
        appropriate safeguards for those transfers. We use technical and organizational measures —
        including row-level security on our database, authenticated-only uploads, and encrypted
        secrets — to protect your data, though no system can be perfectly secure.
      </p>

      <h2>10. Changes</h2>
      <p>
        We may update this policy as the product evolves. Material changes will be reflected by the
        &ldquo;last updated&rdquo; date above and, where appropriate, an in-app notice.
      </p>
    </LegalDoc>
  );
}
